server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineBlog
spring.datasource.username=postgres
spring.datasource.password=pswd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.freemarker.expose-request-attributes=true
spring.freemarker.cache=false
spring.freemarker.template-loader-path=file:src/main/resources/templates/ 
spring.freemarker.suffix:.ftl